apiVersion: v1 
kind: Service 
metadata:
  name: vprocache01
spec:
  ports:
    - port: 11211
      targetPort: vprocache01-port
      protocal: TCP 
  selector:
    app: vprocache01
  type: ClusterIP