apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromem01
  labels:
    app: vpromem01
spec:
  selector:
    matchLabels:
      app: vpromem01
  replicas: 1
  template:
    metadata:
      labels:
        app: vpromem01
    spec:
      containers:
        - name: vpromem01
          image: memcached
          ports:
            - name: vpromem01-port
              containerPort: 11211